### ISSUE TITLE
local build issues

### ISSUE THREAD

**Issue by obkhan** [EKGF/ekg-mm#39]
@jgeluk 

Will edit this further soon to provide more clarity... but here is a list of some issues I encountered. 

I think there are the following causes

1. Folders /home perhaps mounted when using docker ? maybe there needs to be changes to build.sh where a local folder is added, it seems not able to find folders
2. Something I'm doing seems  wrong with the latex-lib build sub tree, there are modifications? Is there a way to specify a branch
3. When in non-docker mode by changing build.sh I get other errors about malformed latex

Pull Latest EKGF/ekg-manifesto and mount at mnt/ekg-manifesto
+ /usr/local/bin/git fetch ekg-manifesto
+ /usr/local/bin/git subtree pull --prefix=mnt/ekg-manifesto ekg-manifesto main --squash
Working tree has modifications.  Cannot add.

Building ekg-manifesto
./build.sh: line 563: ${gitRepoOrgName,,}: bad substitution
/home/build.sh: line 627: cd: ekg-manifesto: No such file or directory
ERROR: Directory ekg-manifesto does not exist
end of docker, rc=1

 ekg-mm  ./build-all.sh
Deleting ./out/ekgf*ekg-manifesto*.pdf
Deleting ./out/ekgf*ekg-mm*.pdf
Going to build ./out/ekgf - ekg-manifesto - *.pdf
Going to build ./out/ekgf - ekg-mm - *.pdf
====================================================================
Building ekg-manifesto
./build.sh: line 563: ${gitRepoOrgName,,}: bad substitution
/home/build.sh: line 627: cd: ekg-manifesto: No such file or directory
ERROR: Directory ekg-manifesto does not exist
end of docker, rc=1

Thoughts - could be with -v mounted folders?
When I do non docker mode 

Transcript written on ekgf-ekg-manifesto-editors-version-0-2-x.log.
******************* lualatex rc=0 ekg-manifesto.tex
*******************
******************* biber ekgf-ekg-manifesto-editors-version-0-2-x
*******************
INFO - This is Biber 2.16
INFO - Logfile is 'ekgf-ekg-manifesto-editors-version-0-2-x.blg'
INFO - DEBUG mode: all messages are logged to 'ekgf-ekg-manifesto-editors-version-0-2-x.blg'
ERROR - ekgf-ekg-manifesto-editors-version-0-2-x.bcf is malformed, last biblatex run probably failed. Deleted ekgf-ekg-manifesto-editors-version-0-2-x.bbl
INFO - ERRORS: 1
******************* biber rc=2 ekgf-ekg-manifesto-editors-version-0-2-x

**Comment by jgeluk** [comment]
Tbh, the `build.sh` script is a bit "deprecated", I always directly use the `latexmk` command these days:

```
latex_document_mode=release-version latex_document_main=ekg-mm latex_customer_code=ekgf latexmk -gg -pvc
```

But that assumes you're not running it with docker...

**Comment by jgeluk** [comment]
See https://github.com/ekgf/ekg-mm#build-steps
